### ISSUE TITLE
Очепятка в xrDXT?

### ISSUE THREAD

**Issue by redpython** [abramcumner/xray15#1]
.\utils\xrDXT\dds\tPixel.h:1343: return cubeFaces[0].height();
.\utils\xrDXT\dds\tPixel.h:1652: return cubeFaces[0].height();

Похоже на последствия копипаста :)

**Comment by Xottab-DUTY** [comment]
Оно самое, об этом тут писали и ещё много о чём: https://www.viva64.com/ru/b/0405/

**Comment by abramcumner** [comment]
Зафикшу

**Comment by redpython** [comment]
Ради великого перфекционизма же :)

**Comment by redpython** [comment]
Буду замусоривать этот топик.
Что-то подсказывает, что в конце должен быть радиус
`.\xray\xrCore\_cylinder.h:187: BOOL _valid (const _cylinder<T>& c) { return _valid(c.m_center) && _valid(c.m_direction) && _valid(c.m_height) && _valid(c.m_height); }`

**Comment by abramcumner** [comment]
все-все, уже пушу :)
