### ISSUE TITLE
White border around the screen

### ISSUE THREAD

**Issue by Xottab-DUTY** [abramcumner/xray15#12]
Is there a way to hide it?

(open the image in the new tab)
![](https://media.discordapp.net/attachments/422693053434691585/954467132480045066/ss_paps_03-17-22_20-27-34_marsh.jpg)

**Comment by abramcumner** [comment]
> Is there a way to hide it?

Yes. [Fix](https://bitbucket.org/stalker/xray-csky_borscht_sdk/commits/ed7a07183d7d452e8e1eac3cdaf4100dbf92caa9)

**Comment by Xottab-DUTY** [comment]
There's also an option:
![](https://media.discordapp.net/attachments/422693053434691585/954471326951804938/ss_paps_03-18-22_21-05-58_fake_level.jpg?width=1099&height=618)
