### ISSUE TITLE
Актуальный билд эт какой?

### ISSUE THREAD

**Issue by aka-sektor** [abramcumner/xray15#2]
В релизах 1.5.10-12 крайняя версия, но меньше суток назад там чет правилось.

Выходит пока в исходниках актуальная версия? Когда её соберут?

**Comment by abramcumner** [comment]
На главной странице есть зеленая плашка "build passing". Если по ней тыкнуть, то можно выйти на собранные бинарники. Выбираешь платформу(Win32 или x64) и переходишь во вкладку ARTIFACTS, там архивы с собранным движком.

> Выходит пока в исходниках актуальная версия? Когда её соберут?
Собирается каждая залитая правка.

**Comment by aka-sektor** [comment]
А в релизы добавить лень или...

**Comment by abramcumner** [comment]
Ну релизы из одной правки по типу 1.5.10-12 мне не понравились.  А так кажется, что на релиз еще не наработано. Надо конечно хотя бы по времени раз в месяц релиз делать.

**Comment by abramcumner** [comment]
Итого: актуальный билд через "build passing" и ежемесячные релизы.
