### ISSUE TITLE
Какие версии Windows поддерживаются?

### ISSUE THREAD

**Issue by aka-sektor** [abramcumner/xray15#4]
Похоже у всех надо это спрашивать, но... тут нету инфы.

Оригинальный ЧН, имел сис.требования Windows: 2000 (SP4)/ XP (SP2)

Тут как?

Да, и какие 3rd party требуются для работы?

**Comment by abramcumner** [comment]
>= windows 7

**Comment by aka-sektor** [comment]
Vista? А выше?

**Comment by abramcumner** [comment]
парсер съел знак больше :) Windows 7 и старше.

**Comment by aka-sektor** [comment]
А виста что?

**Comment by abramcumner** [comment]
Виста как и ХП :)
Это же все от лукавого. ">= Windows 7"  - потому, что в студии тулчейн используется, который официально с виндовс 7. Можно еще выбрать тулчейн ">=Windows XP". В реальности я запускаю движок на виндовс 7 и в команде борща на вин 2008. Ну и когда-то вроде я один раз запускал на вин 10.

> Да, и какие 3rd party требуются для работы?

На последних сборках c++ Redistributable 2017
