### ISSUE TITLE
Как исходники скачать?

### ISSUE THREAD

**Issue by aka-sektor** [abramcumner/xray15#7]
В релизах архивы есть, прошлых версий.

А с новыми как? В "build passing" нету.

Может создашь Job?

**Comment by KRodinn** [comment]
Сори, что влезаю, но @aka-sektor походу заняться нечем просто.

**Comment by abramcumner** [comment]
> Говоришь так, будто тебя это как-то напрягает.
Просто не понял, что за Job и что он должен делать.

Когда переходишь по кнопке "Build Passing" на appveyor, то там показывается текст коммита и есть набо цифробукв типа 7d6a0a93 - это ссылка на коммит в гитхабе, для которого делается сборка. По ней можно вернуться на гитхаб и скачать исходники именно той версии, которая собралась.

**Comment by abramcumner** [comment]
> Сори, что влезаю, но @aka-sektor походу заняться нечем просто.
Не согласен. Очень лояльный пользователь и тестер по совместительству. Именно так видят всю нашу возню обычные моддеры, для которых по сути эти движки и делаются.

**Comment by aka-sektor** [comment]
>  вернуться на гитхаб и скачать

Снова не то. Нужна ссылка как в релизах: https://github.com/abramcumner/xray15/archive/1.5.10-12.zip

Четко видно версию.

Ну куда мне: https://codeload.github.com/abramcumner/xray15/zip/7d6a0a93e0ebbd0cd6356df356f08486e58e9bbc

А если после залива новой версии ссылка поменяется? Или нет, по ней будет старая версия.
Хорошо четко знать.

Job было бы идеально.

**Comment by KRodinn** [comment]
> Именно так видят всю нашу возню обычные моддеры, для которых по сути эти движки и делаются.

Ну не знаю, по-моему мнению, сборка движков и тп. - это не для обычных моддеров вообще.
А для тех, кто в этом хоть что-то понимает. Обычные юзеры в большинстве случаев криво соберут, да и адаптировать что-либо (какой нибудь глобальный мод например) к этим движкам вряд ли смогут.

**Comment by abramcumner** [comment]
> А если после залива новой версии ссылка поменяется? Или нет, по ней будет старая версия.
Ссылка точно не поменяется - это уникальный идентификатор коммита.

Про архив с исходниками подумаю.

**Comment by aka-sektor** [comment]
> не для обычных моддеров вообще

Считаешь сложно изменить .cpp файл имея на руках готовые правки?
https://www.gameru.net/forum/index.php?showtopic=67297

**Comment by KRodinn** [comment]
> Считаешь сложно изменить не профу .cpp файл имея на руках готовые правки?

Ага, смотря кто правит и как. Внося правки в С++ код, надо хотя бы немного понимать, что это такое и как оно работает.
Ну ИМХО конечно.
И да, я сам далеко не профессионал, если что.
Всё, ухожу...

**Comment by aka-sektor** [comment]
> надо хотя бы немного понимать

Так понимаем, немного... не новички зеленые.

**Comment by redpython** [comment]
С моей скромной точки зрения, непрограммисту собирабельный движок типа этого может пригодиться лишь для экспериментов типа "собрать дебаг версию/поменять константу/раскомментировать закомментированное/безуспешно попытаться исправить баг с болтами, заманаться и забить". Польза от данных действий околонулевая. 

Смысла создавать архив исходников каждой собранной версии точно нет, если они будут без истории изменений. А если с историей - то зачем дублировать этот репозиторий в виде ещё одного архива? 

И вообще, каждый должен заниматься своим делом: моделлер моделить, а кодер кодить. Так даже Ясенев говорил :) и боржч тоже доказал, что это куда продуктивнее, чем если пытаться делать наоборот.

**Comment by aka-sektor** [comment]
>  боржч тоже доказал

Громко сказано, нет?

**Comment by redpython** [comment]
>Громко сказано, нет?

Ну ты же как-то здесь оказался :)

**Comment by aka-sektor** [comment]
> как-то здесь оказался :)

Почему как-то? Вообще я отсюда: https://www.gameru.net/forum/index.php?showtopic=71178&st=0&p=1640044&#entry1640044

**Comment by redpython** [comment]
И я об этом. Возможно, между борщом и хреем 1.8 существует пространственно-временная связь, но это ещё не доказано.

**Comment by abramcumner** [comment]
В общем архивы с исходниками будут делаться гитхабом для релизов. Релизы буду стараться делать чаще. А тот, кто сумел добраться до собранных бинарников на аппвейор, сумеет вернуться на гитхаб за исходниками.
